version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER:     odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB:       postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  odoo:
    image: cri-odoo-custom:v1
    ports:
      - "8069:8069"
    depends_on:
      - db
    volumes:
      - odoo_data:/var/lib/odoo

volumes:
  postgres_data:
  odoo_data:
